const allConcept = [
  {
    id: "tetnc",
    img: [],
    title: "Tết ngoại cảnh",
    // idPhoto: "photo-gallery-tet-nc",
  },
  {
    id: "tetstu",
    img: [],
    title: "Tết trong studio",
    // idPhoto: "photo-gallery-tet-nc",
  },
  {
    id: "sinhnhat",
    img: [
      "assets/imagess/concept/sinhnhat/sn1.jpg",
      "assets/imagess/concept/sinhnhat/sn2.jpg",
      "assets/imagess/concept/sinhnhat/sn3.jpg",
      "assets/imagess/concept/sinhnhat/sn4.jpg",
      "assets/imagess/concept/sinhnhat/sn5.jpg",
      "assets/imagess/concept/sinhnhat/sn6.jpg",
      "assets/imagess/concept/sinhnhat/sn7.jpg",
      "assets/imagess/concept/sinhnhat/sn8.jpg",
      "assets/imagess/concept/sinhnhat/sn9.jpg",
      "assets/imagess/concept/sinhnhat/sn10.jpg",
      "assets/imagess/concept/sinhnhat/sn12.jpg",
      "assets/imagess/concept/sinhnhat/sn13.jpg",
      "assets/imagess/concept/sinhnhat/sn14.jpg",
      "assets/imagess/concept/sinhnhat/sn15.jpg",
      "assets/imagess/concept/sinhnhat/sn16.jpg",
      "assets/imagess/concept/sinhnhat/sn17.jpg",
      "assets/imagess/concept/sinhnhat/sn18.jpg",
      "assets/imagess/concept/sinhnhat/sn19.jpg",
      "assets/imagess/concept/sinhnhat/sn20.jpg",
      "assets/imagess/concept/sinhnhat/sn21.jpg",
      "assets/imagess/concept/sinhnhat/sn22.jpg",
      "assets/imagess/concept/sinhnhat/sn23.jpg",
      "assets/imagess/concept/sinhnhat/sn24.jpg",
      "assets/imagess/concept/sinhnhat/sn25.jpg",
      "assets/imagess/concept/sinhnhat/sn26.jpg",
      "assets/imagess/concept/sinhnhat/sn27.jpg",
      "assets/imagess/concept/sinhnhat/sn28.jpg",
      "assets/imagess/concept/sinhnhat/sn29.jpg",
    ],
    title: "Sinh nhật",
    // idPhoto: "photo-gallery-tet-stu",
  },
  {
    id: "couple",
    img: [
      "assets/imagess/concept/couple/c1.jpg",
      "assets/imagess/concept/couple/c2.jpg",
      "assets/imagess/concept/couple/c3.jpg",
      "assets/imagess/concept/couple/c4.jpg",
      "assets/imagess/concept/couple/c5.jpg",
      "assets/imagess/concept/couple/c6.jpg",
      "assets/imagess/concept/couple/c7.jpg",
      "assets/imagess/concept/couple/c8.jpg",
      "assets/imagess/concept/couple/c9.jpg",
      "assets/imagess/concept/couple/c10.jpg",
      "assets/imagess/concept/couple/c11.jpg",
    ],
    title: "couple",
    // idPhoto: "photo-gallery-tet-nc",
  },
  {
    id: "profile",
    img: [
      "assets/imagess/concept/profile/p21.jpg",
      "assets/imagess/concept/profile/p23.jpg",
      "assets/imagess/concept/profile/p22.jpg",
      "assets/imagess/concept/profile/p1.jpg",
      "assets/imagess/concept/profile/p2.jpg",
      "assets/imagess/concept/profile/p3.jpg",
      "assets/imagess/concept/profile/p4.jpg",
      "assets/imagess/concept/profile/p5.jpg",
      "assets/imagess/concept/profile/p6.jpg",
      "assets/imagess/concept/profile/p7.jpg",
      "assets/imagess/concept/profile/p8.jpg",
      "assets/imagess/concept/profile/p9.jpg",
      "assets/imagess/concept/profile/p10.jpg",
      "assets/imagess/concept/profile/p11.jpg",
      "assets/imagess/concept/profile/p12.jpg",
      "assets/imagess/concept/profile/p13.jpg",
      "assets/imagess/concept/profile/p14.jpg",
      "assets/imagess/concept/profile/p15.jpg",
      "assets/imagess/concept/profile/p16.jpg",
      "assets/imagess/concept/profile/p17.jpg",
      "assets/imagess/concept/profile/p18.jpg",
      "assets/imagess/concept/profile/p24.jpg",
      "assets/imagess/concept/profile/p19.jpg",
      "assets/imagess/concept/profile/p20.jpg",
    ],
    title: "profile",
    // idPhoto: "photo-gallery-tet-nc",
  },
  {
    id: "nangtho",
    img: [
      "assets/imagess/concept/nangtho/nt1.jpg",
      "assets/imagess/concept/nangtho/nt2.jpg",
      "assets/imagess/concept/nangtho/nt3.jpg",
      "assets/imagess/concept/nangtho/nt4.jpg",
      "assets/imagess/concept/nangtho/nt5.jpg",
      "assets/imagess/concept/nangtho/nt6.jpg",
      "assets/imagess/concept/nangtho/nt7.jpg",
      "assets/imagess/concept/nangtho/nt8.jpg",
      "assets/imagess/concept/nangtho/nt9.jpg",
      "assets/imagess/concept/nangtho/nt10.jpg",
      "assets/imagess/concept/nangtho/nt11.jpg",
      "assets/imagess/concept/nangtho/nt12.jpg",
      "assets/imagess/concept/nangtho/nt13.jpg",
      "assets/imagess/concept/nangtho/nt14.jpg",
      "assets/imagess/concept/nangtho/nt15.jpg",
      "assets/imagess/concept/nangtho/nt16.jpg",
      "assets/imagess/concept/nangtho/nt17.jpg",
      "assets/imagess/concept/beauty/b2.jpg",
      "assets/imagess/concept/nangtho/nt18.jpg",
      "assets/imagess/concept/nangtho/nt19.jpg",
      "assets/imagess/concept/nangtho/nt20.jpg",
      "assets/imagess/concept/nangtho/nt21.jpg",
      "assets/imagess/concept/nangtho/nt22.jpg",
      "assets/imagess/concept/nangtho/nt23.jpg",
      "assets/imagess/concept/nangtho/nt24.jpg",
      "assets/imagess/concept/nangtho/nt25.jpg",
      "assets/imagess/concept/beauty/b4.jpg",
      "assets/imagess/concept/nangtho/nt26.jpg",
      "assets/imagess/concept/nangtho/nt27.jpg",
      "assets/imagess/concept/nangtho/nt28.jpg",
      "assets/imagess/concept/beauty/b3.jpg",
      "assets/imagess/concept/nangtho/nt29.jpg",
      "assets/imagess/concept/nangtho/nt30.jpg",
      "assets/imagess/concept/nangtho/nt31.jpg",
      "assets/imagess/concept/nangtho/nt32.jpg",
      "assets/imagess/concept/nangtho/nt33.jpg",
      "assets/imagess/concept/nangtho/nt34.jpg",
      "assets/imagess/concept/nangtho/nt35.jpg",
      "assets/imagess/concept/nangtho/nt36.jpg",
      "assets/imagess/concept/beauty/b1.jpg",
      "assets/imagess/concept/nangtho/nt37.jpg",
      "assets/imagess/concept/nangtho/nt38.jpg",
      "assets/imagess/concept/nangtho/nt39.jpg",
      "assets/imagess/concept/beauty/b6.jpg",
      "assets/imagess/concept/nangtho/nt40.jpg",
      "assets/imagess/concept/nangtho/nt41.jpg",
      "assets/imagess/concept/nangtho/nt42.jpg",
      "assets/imagess/concept/beauty/b5.jpg",
    ],
    title: "nàng thơ",
    // idPhoto: "photo-gallery-tet-nc",
  },
];

const options = [
  { label: "Tết ngoại cảnh", value: "tetnc" },
  { label: "Tết trong studio", value: "tetstu" },
  { label: "Sinh nhật", value: "sn" },
  { label: "Couple", value: "couple" },
  { label: "Profile", value: "profile" },
  { label: "Beauty", value: "beauty" },
  { label: "Nàng thơ", value: "nt" },
];

export { options, allConcept };
